server:
  port: 8081

spring:
  application:
    name: auth
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/school_auth_service
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret:
    access: aa7sr4lm21fr5fq0y0qyhjv8221r8ro3ee1iwj6sj4i1qppjin

  # For map several instances (also set server.port: 0)
  #instance:
  #  instance-id: ${spring.application.name}:${random.uuid}
