server:
  port: 8765

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8000"
              - "http://localhost"
            allowedHeaders: "*"
            allowedMethods: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka