server:
  port: 8765

spring:
  application:
    name: gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
