server:
  port: 8080

spring:
  application:
    name: file

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

file:
  root-path: /Users/Shared/project-files

  # For map several instances (also set server.port: 0)
  #instance:
  #  instance-id: ${spring.application.name}:${random.uuid}