grpc:
  server:
    port: 9001

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/school_file_service
    username: postgres
    password: password

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update